accounts/urls.py
from django.urls import path
from accounts import views


app_name = 'accounts'

urlpatterns = [
    path('', views.Home.as_view(), name='account'),
    path('validate/', views.CreateUser.as_view(), name='create'),
    path('login/', views.UserLogin.as_view(), name='login'),
    path('process/form/', views.ProcessModelForm.as_view(), name='form'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from accounts.views import CustomPasswordResetConfirmView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('social_network.urls')),

    path(
        'reset-password/',
        auth_views.PasswordResetView.as_view(),
        name='password_reset'
    ),

    path(
        'reset-password/done/', 
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'
    ),
    path(
        'reset-password/<uidb64>/<token>/', 
        CustomPasswordResetConfirmView.as_view(),
        name='password_reset_confirm'
    ),

    path(
        'reset-password/complete/', 
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += path("__debug__/", include("debug_toolbar.urls")),

social_network/urls.py
from django.urls import path
from social_network import views

urlpatterns = [
    path("feed/", views.feed, name="feed"),
    path("process_image/", views.process_image, name="process_image"),
    path("logout/", views.logout_view, name="logout"),
    path("create_status/", views.create_status, name="create_status"),
    path("status/<str:user>", views.show_status_of_a_user, name='all_status'),
    path(
        "feed/search_user/<str:user>", views.search_users, name='search_users'
    ),
    path("feed/add/notify/<str:user>", views.send_notify_add_friend, name='notify'),
    path("feed/add/<str:user>/<int:notify_id>/", views.add_friends, name='add_friends'),

    path(
        "feed/add/delete/post/<str:pk>", views.delete_post, name='delete_post'
    ),

    path("feed/add/new/post", views.add_post, name='add_post'),

    path(
        "feed/counter/likes/<int:post_id>/<int:likes>",
        views.num_likes_of_post,
        name='counter_Likes'
    ),

    path(
        "feed/delete/friend/<str:pk>",
        views.delete_friend,
        name='delete_friend'
    ),

]

social_network/models.py
from django.db import models
from django import forms
from django.contrib.auth.models import User


class ProfilePersonal(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, blank=True, related_name='my_profile'
    )

    profile_image = models.ImageField(
        upload_to='social_network/covers/profile/', blank=True, default=None
    )

    def __str__(self) -> str:
        return str(self.user)


class Status(models.Model):
    status_image = models.ImageField(
        upload_to='social_network/covers/status', blank=True
    )

    usuario = models.ForeignKey(
        ProfilePersonal, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return str(self.status_image)


class Friends(models.Model):
    friend = models.ForeignKey(
        ProfilePersonal, on_delete=models.CASCADE, blank=True,
        related_name='reverse_friend'
    )

    user_reference = models.ForeignKey(
        ProfilePersonal, on_delete=models.CASCADE, blank=True
    )

    def __str__(self) -> str:
        return f"{str(self.friend)} is a friend of {self.user_reference}"


class Post(models.Model):
    user = models.ForeignKey(
        ProfilePersonal, on_delete=models.CASCADE, blank=False
    )
    text_post = models.TextField(max_length=300)
    public = models.CharField(max_length=10, null=True)
    likes = models.IntegerField(default=0)
    post_image = models.ImageField(
        upload_to='social_network/covers/post/', blank=True, null=True
    )

    def __str__(self) -> str:
        return f"Post of {str(self.user)}"


class ProfilePersonalModel(forms.ModelForm):
    class Meta:
        model = ProfilePersonal
        fields = ['profile_image']


class PostModel(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['post_image']
        labels = {
            'post_image': ''
        }


class StatusModel(forms.ModelForm):
    class Meta:
        model = Status
        fields = ['status_image']


class Notifications(models.Model):
    sender = models.ForeignKey(
        ProfilePersonal, on_delete=models.PROTECT, blank=True, null=True,
        related_name='sender_notifications'
    )
    read = models.BooleanField(default=False)
    recipient_user = models.ForeignKey(
        ProfilePersonal, on_delete=models.PROTECT, blank=True, null=True,
        related_name='received_notifications'
    )
    verb = models.CharField(max_length=255, blank=True, null=True)

    # unread = NotificationManager()

    def mark_as_read(self):
        self.read = True
        self.save()

social_network/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .models import ProfilePersonal, ProfilePersonalModel, Notifications
from .models import Status, StatusModel, Post, PostModel
from .models import Friends
from django.http import JsonResponse
from django.templatetags.static import static
from django.db.models import F


@login_required
def feed(request):
    profile = ProfilePersonal.objects.select_related('user')\
        .get(user__username=request.user.username)
    fields_of_model_profile_image = ProfilePersonalModel()
    send_img_post = PostModel()
    status_fields = StatusModel()
    friend_all = Friends.objects.filter(user_reference=profile)\
        .select_related('friend', 'friend__user')\
        .prefetch_related('friend__status_set',)\
        .annotate(friend_name=F('friend__user__username'))

    post = Post.objects.filter(public='public').select_related(
        'user', 'user__user'
        ).annotate(username=F('user__user__username'))\
        .order_by('-id')

    my_status = Status.objects.filter(usuario=profile)\
        .select_related('usuario', 'usuario__user').last()

    my_notifications = Notifications.objects.filter(
        recipient_user=profile, read=False
    )
    notification_count = my_notifications.count()

    return render(
        request, 'social_network/partials/notify.html',
        context={
            'profile_data': profile,
            'fields': fields_of_model_profile_image,
            'status_fields': status_fields,
            'post_field': send_img_post,
            'friend_all': friend_all,
            'posts': post,
            'my_status': my_status,
            'notification': my_notifications,
            'notify_count': notification_count
        }
    )


#  change profile image
@login_required()
def process_image(request):
    if request.method == 'POST':
        form = ProfilePersonalModel(request.POST, request.FILES)
        username = request.user.username
        if form.is_valid():
            instance_of_profile = ProfilePersonal.objects.get(
                user__username=username
            )
            # delete the old profile image before save the new one
            if instance_of_profile.profile_image:
                instance_of_profile.profile_image.delete(save=True)

            instance_of_profile.profile_image = request.FILES.get(
                'profile_image', instance_of_profile.profile_image
            )

            instance_of_profile.save()
            return redirect('feed')
    return redirect('feed')


@login_required()
def create_status(request):
    if request.method == 'POST':
        form = ProfilePersonalModel(request.POST, request.FILES)
        form_image = form.files.get('status_image')
        user = ProfilePersonal.objects.get(
            user__username=request.user.username
        )
        Status.objects.create(usuario=user, status_image=form_image)
    return redirect('feed')


@login_required()
def show_status_of_a_user(request, user):
    status_of_user = Status.objects.filter(usuario__user__username=user)\
        .select_related('usuario', 'usuario__user')

    status_list = list()

    for status in status_of_user:
        user_status = {
            'user': status.usuario.user.username,
            'profile_image': status.usuario.profile_image.url
            if status.usuario.profile_image else (
                static("img/without_user.png")
            ),
            'status_image': status.status_image.url,
        }

        status_list.append(user_status)
    response_data = {'user_status': status_list}

    return JsonResponse(response_data)


@login_required()
def search_users(request, user):
    new_user = ProfilePersonal.objects.filter(user__username__icontains=user)\
        .exclude(user__username=request.user.username)
    user_list = []

    for people in new_user:
        user_data = {
            'username': people.user.username,
            'email': people.user.email,
            'image': request.build_absolute_uri(people.profile_image.url)
            if people.profile_image else (
                static("img/without_user.png")
            ),
        }

        user_list.append(user_data)
    response_data = {'user': user_list}

    return JsonResponse(response_data)


def send_notify_add_friend(request, user):
    sender = ProfilePersonal.objects.get(user__username=request.user.username)
    recipient = ProfilePersonal.objects.get(user__username=user)

    Notifications.objects.create(
        sender=sender,
        recipient_user=recipient,
        verb=f"{request.user.username} enviou uma solicitação",
    )
    return redirect('feed')


@login_required()
def add_friends(request, user, notify_id):
    Notifications.objects.get(id=notify_id).mark_as_read()
    friend = ProfilePersonal.objects.get(user__username=user)
    reference_user = ProfilePersonal.objects.get(
        user__username=request.user.username
    )

    user_is_a_friend = Friends.objects.filter(
        user_reference=reference_user, friend=friend
    )

    if user_is_a_friend.exists():
        pass
    else:
        Friends.objects.create(
            friend=friend,
            user_reference=reference_user
        )
        Friends.objects.create(
            friend=reference_user,
            user_reference=friend,
        )
#   TODO: VALIDAR PARA N ENVIAR MAIS DE UMA NOTIFICAÇAO
#   TODO: CRIAR TEMPLATE Q MOSTRA AS NOTIFICAÇOES
    return redirect('feed')


@login_required()
def delete_friend(request, pk):
    try:
        Friends.objects.get(
            pk=pk
        ).delete()
    except Exception as e:
        print('error', e)
    return redirect('feed')


@login_required()
def add_post(request):
    user = ProfilePersonal.objects.get(
        user__username=request.user.username
    )

    form = PostModel(request.POST, request.FILES)
    if form.is_valid():
        new_post = request.POST.get('thinking')
        public_or_private = request.POST.get('post_form_text')

        Post.objects.create(
            user=user,
            text_post=new_post,
            public=public_or_private,
            post_image=request.FILES.get('post_image')
        )

    return redirect('feed')


@login_required()
def num_likes_of_post(reques, post_id, likes):
    try:
        post = Post.objects.get(id=post_id)
        post.likes = likes
        post.save()
    except Post.DoesNotExist:
        pass

    return redirect('feed')


@login_required()
def delete_post(request, pk):
    try:
        post = Post.objects.get(pk=pk)
        post.post_image.delete()
        post.delete()
    except: # noqa
        pass
    return redirect('feed')


@login_required()
def logout_view(request):
    logout(request)
    return redirect('accounts:account')

social_network/templates/social_network/partials/feed.html
{% extends "social_network/partials/left_menu.html" %}
{% load static %}



{% block feed %}
    {% block show_all_friends %} {% endblock show_all_friends %}


    <div class="content_add">Add with succes</div>
    <div class="gerenal_icons_mobile" title="change profile image">
        <label for="id_profile_image">
            <div class="image_profile">
                {% if profile_data.profile_image %}
                    <img src=" {{profile_data.profile_image.url}} " alt="">
                {% else %}
                    <img src="{% static "img/without_user.png" %}" alt="">
                {% endif %}

            </div>
        </label>
        <form action=" {% url "process_image" %} " method='POST' enctype="multipart/form-data" id='send_profile_image'>
            {% csrf_token %}
            {{fields.profile_image}}
        </form>
        <div class="user_info">
            <p>{{profile_data.user.username|capfirst}}</p>
        </div>
        <div class="icons_mobile">
            <i class="fa-solid fa-user-group friends_open_mobile"></i>

            <i class="fa-solid fa-bell"></i>
            <i id='mobile_notificationb' class="fa-solid fa-message">
                <span class="notification_counter">
                    {% if notify_count < 99 %}
                        {{notify_count}}
                    {% else %}
                        99+
                    {% endif %}
                </span>
            </i>
            <a href="/logout/ "><i class="fa-solid fa-right-from-bracket"></i></a>
        </div>
    </div>
    <div class="feed_search_user">
        <form action="" class="submit" onsubmit="return false;">
            <label for="all_users" class="search_all">
                <i class="fa-solid fa-magnifying-glass"></i>
                <input class="input" type="text" id="all_users" placeholder="Search in Friend Sync">
            </label>
            <div id="suggestions" class="suggestions" data-url="{% url 'accounts:account' %}">
            </div>
        </form> 
    </div>

    <div class="status">
            <form action=" {% url "create_status" %} " method='POST' enctype="multipart/form-data" id="send_status">
                {% csrf_token %}
                {{status_fields.status_image}}
            </form>

        <button class="arrow-left control">◀</button>
        <button class="arrow-right control">▶</button>
        <div class="carousel">
            <label for="id_status_image">
                <div class="create_status_container">
                    <div class="create_status_image">
                        {% if profile_data.profile_image %}
                            <img src=" {{profile_data.profile_image.url}} " alt="">
                        {% else %}
                            <img src="{% static "img/without_user.png" %}" alt="">
                        {% endif %}
                    </div>
                    <div class="icon_create_status">
                        <div class="icon_plus"> <i class="fa-solid fa-plus"></i> </div>
                        <p>Create status</p>
                    </div>
                </div>
            </label>

            {% if my_status %}
                <a href=" {% url 'all_status' my_status.usuario.user %}" data-link="{{my_status.usuario.user}}">
                    <div class="story item current-item">
                        <div class="user_picture_story">
                            {% if my_status.usuario.profile_image %}
                                <img src="{{ my_status.usuario.profile_image.url}}" alt="">
                            {% else %}
                                <img src="{% static "img/without_user.png" %}" alt="">
                            {% endif %}
                        </div>
                        <p>{{ my_status.usuario.user }}</p>
                        <img src="{{my_status.status_image.url}}" alt="">
                    </div>
                </a>
            {% endif %}
            
            {% for friends in friend_all %}
            
            
                {% if friends.friend.status_set.all %}
                    <a href=" {% url "all_status" friends.friend_name%}" data-link="{{friends.friend_name}}">
                        <div class="story item current-item">
                            <div class="user_picture_story">
                                {% if friends.friend.profile_image %}
                                    <img src="{{ friends.friend.profile_image.url }}" alt="">
                                {% else %}
                                    <img src="{% static "img/without_user.png" %}" alt="">
                                {% endif %}
                            </div>
                            <p>{{ friends.friend_name }}</p>
                            {% for status in friends.friend.status_set.all %}
                                {% if forloop.last %}
                                    <img src="{{ status.status_image.url }}" alt="">
                                {% endif %}
                            {% endfor %}
                        </div>
                    </a>
                {% endif %}
            {% endfor %}
        </div>
    </div>

    <div class="create_post_content">
        <div class="user_and_textarea">
            <div class="user_picture_story user_create_post">
                {% if profile_data.profile_image %}
                    <img src=" {{profile_data.profile_image.url}} " alt="">
                {% else %}
                    <img src="{% static "img/without_user.png" %}" alt="">
                {% endif %}
            </div>

            <form action=" {% url "add_post" %} " method="post" class="text" enctype="multipart/form-data">
                {% csrf_token %}
                <textarea name="thinking" id="" cols="30" rows="1"></textarea>
                <input name="post_form_text" type="checkbox" id="post_form_checkbox" value="public" checked>
                {{post_field.post_image}}

            </form>

            <span class="span_send_post" ><i class="fa-solid fa-share"></i></span>
            <span class="text_for_new_post"><P>What is on your mind, {{profile_data.user.username|capfirst}}</P></span>
        </div>

        <div class="public_and_img">
            <class class="public">
                <i class="fa-solid fa-lock-open"></i>
                <p>This post will be public</p>
            </class>

            <div class="send_img_poss">
                <label for="id_post_image" class="id_post_image">
                     <i class="fa-solid fa-image"></i>/
                     <p>picture</p>
                </label>
            </div>
        </div>
        

    </div>
    
    {% for user_post in posts %}
        <div class="show_posts_of_users">
            <div class="user_post_content">

                <div class="user_and_username post_user_and_picture">
                    <div class="image_profile image_profile_feed">
                        {% if user_post.user.profile_image %}
                            <img src=" {{user_post.user.profile_image.url}} " alt="">
                        {% else %}
                            <img src="{% static "img/without_user.png" %}" alt="">
                        {% endif %}
                    </div>
                    <p>{{user_post.username}}</p>


                    {% if user_post.user.user.id == profile_data.user.id %}
                        <div class="delete_content" >
                            <span class="options_post" ><i class="fas fa-ellipsis-h"></i></span>
                            <div class="delete_post"><a href=" {% url "delete_post" user_post.pk %} "><span class="span_delete">Delete</span></a></div>
                        </div>
                    {% endif %}

                </div>
                
                <div class="text_post">
                    <div class="text_content">
                        <pre>{{user_post.text_post}}</pre>
                    </div>
                </div>

                {% if user_post.post_image %}
                    <div class="img_post">
                        <img src="{{user_post.post_image.url}}" alt="">
                    </div>
                {% endif %}

                <div class="social_icons" id="{{user_post.pk}}">
                    <div class="like">
                        <i class="fa-regular fa-thumbs-up"></i>
                        <p>like</p>
                    </div>
                    <div class="comments">
                        <i class="fa-regular fa-comments"></i>
                        <p>commentes</p>
                    </div>

                    <div class="num_likes">
                        {{user_post.likes}}: likes
                    </div>
                </div>
            </div>
        </div>

        
    {% endfor %}

{% endblock feed %}



{% comment %} {% if notification %}
{% for n in notification %}
    {{n.verb|safe}}
{% endfor %}
{% endif %} {% endcomment %}

social_network/templates/social_network/partials/friends.html
{% extends "social_network/partials/show_status.html" %}
{% load static %}

{% block friends %}
    {% for friend in friend_all %}
        <div class="friend_container">
            <div class="profile_container">
                {% if friend.friend.profile_image %}
                    <img src=" {{friend.friend.profile_image.url}} " alt="">
                {% else %}
                    <img src="{% static "img/without_user.png" %}" alt="">
                {% endif %}
            </div>
            <p> {{friend.friend_name}} </p>
        </div>
    {% endfor %}
{% endblock friends %}


{% block show_all_friends %}    
    <div class="all_friends">
        <div class="friends_container">
            <div class="close_show_friends">
                <p>Friends</p>
                <i class="fa-solid fa-xmark close"></i>
            </div>
            {% for friend in friend_all %}
                <div class="friend_user" id="{{ friend.id }}">
                    <div class="profile_container profile_container_all_friends">
                        {% if friend.friend.profile_image %}
                            <img src=" {{friend.friend.profile_image.url}} " alt="">
                        {% else %}
                            <img src="{% static "img/without_user.png" %}" alt="">
                        {% endif %}
                        <p>{{friend.friend_name}}</p>
                        <button class="all_user_delete">
                            <a href=" {% url "delete_friend" friend.id%} ">Delete</a>
                        </button>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock show_all_friends %}

social_network/templates/social_network/partials/left_menu.html
{% extends "social_network/feed.html" %}
{% load static %}




{% block left_menu %}
    <div class="left_menu_fixed">
        <div class="left_menu_content">
            <label for="id_profile_image">
                <div class="image_profile" title="change profile image">
                    {% if profile_data.profile_image %}
                        <img src=" {{profile_data.profile_image.url}} " alt="">
                    {% else %}
                        <img src="{% static "img/without_user.png" %}" alt="">
                    {% endif %}
                </div>
            </label>
            <div class="user_info">
                <p>{{profile_data.user.username|capfirst}}</p>
                <p>{{profile_data.user.email|capfirst}}</p>
            </div>

            <form action=" {% url "process_image" %} " method='POST' enctype="multipart/form-data" id='send_profile_image'>
                {% csrf_token %}
                {{fields.profile_image}}
            </form>
           
        </div>
        <div class="left_menu_icons">
            <p>General</p>
            <div class="general_icons">
                <button class="friends_open" ><i class="fa-solid fa-user-group"></i>Friends</button>
                <button class="notify_open">
                    <i class="fa-solid fa-bell"></i>Notifications
                    {% if notification %}
                        <span class="notification_counter">
                            {% if notify_count < 99 %}
                                {{notify_count}}
                            {% else %}
                                99+
                            {% endif %}
                        </span>
                    {% endif %}

                </button>

                <button><i class="fa-solid fa-message"></i>Messages</button>
            </div>
            <p>Private</p>
            <div class="private_icons">
                <button><i class="fa-solid fa-gear"></i>Configurations</button>
                <button><i class="fa-solid fa-circle-question"></i>Support</button>
                <a href="/logout/ "><button><i class="fa-solid fa-right-from-bracket"></i>Logout</button></a>
            </div>
        </div>

    </div>

    
{% endblock left_menu %}

social_network/templates/social_network/partials/notify.html
{% extends "social_network/partials/friends.html" %}
{% load static %}

{% block notication %}
    <div class="background_notify">
        <div class="container_all_notfy">
            <div class="container_notify">
                <p>Notifications</p>

                <div class="close_notify">
                    <i class="fa-solid fa-xmark"></i>
                </div>
            </div>  
               
            {% if notification %}
                {% for notfy in notification %}
                    <div class="container_notfication">
                        <div class="container_user_notfy">
                        <div class="notification_container">
                            {% if notfy.sender.profile_image %}
                                <img src="{{notfy.sender.profile_image.url}}" alt="">
                            {% else %}
                                <img src="{% static "img/without_user.png" %}" alt="">
                            {% endif %}
                            <p class="name_sender_notification">{{notfy.sender}}</p>
                        </div>
                        
                            <div class="buttons_add_delete">
                                <a class="add_button" href="{% url "add_friends" notfy.sender notfy.id %}">Confirm</a>
                                <a class="delete_button" href="">Delete</a>

                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
{% endblock notication %}


<p>{{notfy.sender}}</p>
<div class="profile_container"></div>

social_network/templates/social_network/partials/show_status.html
{% extends "social_network/partials/feed.html" %}

{% load static %}


{% block show_all_status_of_user %}
    <div class="background">
        <div class="status_user_content">
            <button class="left_status">◀</button>
            <button class="right_status">▶</button>
            <i class="fa-solid fa-xmark"></i>
            <div class="status_content"></div>
        </div>
    </div>
{% endblock show_all_status_of_user %}